function cfg = default_config()
% DEFAULT_CONFIG Returns the standard validated LFMT default configuration struct.

cfg = struct();

% 1. Plate Specimen Geometry (AISI 1018 Mild Steel)
cfg.plate = struct(...
    'material', 'mild_steel', ...
    'length_mm', 100.0, ...
    'width_mm', 70.0, ...
    'thickness_mm', 2.3, ...
    'thermal_conductivity', 51.9, ... % W/(m·K)
    'density', 7850.0, ...            % kg/m^3
    'specific_heat', 486.0 ...        % J/(kg·K)
);

% 2. Defect Specification (Silicate Slag Inclusion)
cfg.defects = [
    struct(...
        'id', 1, ...
        'shape', 'cylinder', ...
        'material', 'slag', ...
        'center_x_mm', 50.0, ...
        'center_y_mm', 35.0, ...
        'depth_mm', 0.4, ...
        'diameter_mm', 8.0, ...
        'thickness_mm', 0.5, ...
        'thermal_conductivity', 1.20, ... % W/(m·K)
        'density', 2800.0, ...            % kg/m^3
        'specific_heat', 850.0 ...        % J/(kg·K)
    )
];

% 3. LFMT Excitation & Boundary Conditions
cfg.excitation = struct(...
    'f0_hz', 0.05, ...
    'f1_hz', 0.50, ...
    'duration_s', 10.0, ...
    'q0_w_m2', 5000.0, ...
    'h_conv_w_m2k', 10.0, ...
    'ambient_temp_k', 293.15 ...
);

% 4. Simulation & Solver Configuration
cfg.simulation = struct(...
    'solver_type', 'fem', ... % 'fem' (primary) or 'fdm' (secondary)
    'Nx', 40, ...             % Spatial elements along X (nodes = Nx+1)
    'Ny', 28, ...             % Spatial elements along Y (nodes = Ny+1)
    'Nz', 12, ...             % Spatial elements along Z (nodes = Nz+1)
    'dt_s', 0.02, ...         % Internal solver time-step
    'total_time_s', 10.0 ...  % Total simulation duration
);

% 5. Virtual IR Camera Acquisition
cfg.camera = struct(...
    'cam_nx', 64, ...
    'cam_ny', 64, ...
    'sampling_rate_hz', 25.0, ...
    'frame_rate_hz', 25.0, ...
    'noise_snr_db', [], ...   % Empty [] for clean, or numeric (e.g. 30, 25, 20)
    'noise_seed', 1001 ...
);

% 6. Signal Processing & Detection Settings
cfg.processing = struct(...
    'methods', {{'RAW', 'MF', 'PCT', 'SPCT', 'RPT'}}, ...
    'pct_n_components', 6, ...
    'spct_n_components', 6, ...
    'spct_alpha', 0.05, ...
    'rpt_n_components', 6, ...
    'rpt_seed', 42, ...
    'detection_min_area_px', 3, ...
    'detection_threshold_method', 'otsu' ...
);
end
