function [k_field, rhoCp_field, defect_mask] = assignMaterials(grid, defects, mat_db)
% ASSIGNMATERIALS Maps heterogeneous thermal properties onto 3-D grid
%
% Parameters:
%   grid:        Struct generated by createGrid()
%   defects:     Array of structs or struct with defect specifications:
%                - diameter_mm
%                - depth_mm (canonical depth: front surface to top of defect)
%                - thickness_mm
%                - center_x_mm
%                - center_y_mm
%                - material (optional, defaults to 'slag')
%   mat_db:      Material database from createMaterialDatabase()

if nargin < 3, mat_db = lfmt.createMaterialDatabase(); end
if nargin < 2, defects = []; end

% Default background matrix: Mild Steel
k_steel = mat_db.mild_steel.k;
rhoCp_steel = mat_db.mild_steel.Cv;

k_field = full(k_steel * ones(grid.Nx, grid.Ny, grid.Nz));
rhoCp_field = full(rhoCp_steel * ones(grid.Nx, grid.Ny, grid.Nz));
defect_mask = false(grid.Nx, grid.Ny, grid.Nz);

if isempty(defects)
    return;
end

% Process defect definitions (handle scalar or array of defect structs)
if isstruct(defects)
    n_def = length(defects);
else
    n_def = 0;
end

for d_idx = 1:n_def
    d_cfg = defects(d_idx);
    
    diam_m = d_cfg.diameter_mm * 1e-3;
    if diam_m <= 0, continue; end
    
    rad_m = diam_m / 2.0;
    cx_m = d_cfg.center_x_mm * 1e-3;
    cy_m = d_cfg.center_y_mm * 1e-3;
    z_top_m = d_cfg.depth_mm * 1e-3;
    t_def_m = d_cfg.thickness_mm * 1e-3;
    z_bot_m = z_top_m + t_def_m;
    
    % Material properties for inclusion
    if isfield(d_cfg, 'material') && isfield(mat_db, d_cfg.material)
        mat_inc = mat_db.(d_cfg.material);
    else
        mat_inc = mat_db.slag;
    end
    
    % Spatial logical mask for cylinder: (x-cx)^2 + (y-cy)^2 <= R^2 & z in [z_top, z_bot]
    r_sq = (grid.X - cx_m).^2 + (grid.Y - cy_m).^2;
    in_def = (r_sq <= rad_m^2) & (grid.Z >= z_top_m) & (grid.Z <= z_bot_m);
    
    k_field(in_def) = mat_inc.k;
    rhoCp_field(in_def) = mat_inc.Cv;
    defect_mask = defect_mask | in_def;
end
end
