function db = createMaterialDatabase()
% CREATEMATERIALDATABASE Standard thermophysical material properties for LFMT
%
% Returns a struct containing canonical SI material properties:
%   k:   thermal conductivity [W/(m*K)]
%   rho: density [kg/m^3]
%   Cp:  specific heat capacity [J/(kg*K)]
%   Cv:  volumetric heat capacity [J/(m^3*K)] = rho * Cp

db = struct();

% Mild Steel (AISI 1018) - Base Plate Matrix
db.mild_steel = struct(...
    'name', 'Mild Steel (AISI 1018)', ...
    'k', 51.90, ...
    'rho', 7860.0, ...
    'Cp', 486.0, ...
    'Cv', 7860.0 * 486.0 ...
);

% Slag Inclusion - Subsurface Defect
db.slag = struct(...
    'name', 'Slag Inclusion', ...
    'k', 1.50, ...
    'rho', 2800.0, ...
    'Cp', 800.0, ...
    'Cv', 2800.0 * 800.0 ...
);

% Air (Void Reference)
db.air = struct(...
    'name', 'Air', ...
    'k', 0.026, ...
    'rho', 1.20, ...
    'Cp', 1005.0, ...
    'Cv', 1.20 * 1005.0 ...
);
end
