function geom = geometry(plate_cfg, defects_cfg)
% GEOMETRY Defines parameterized 3D specimen dimensions, defect geometry, and ground truth.
%
% Usage:
%   geom = lfmt.geometry(plate_cfg, defects_cfg)

if nargin < 1 || isempty(plate_cfg)
    plate_cfg = struct('length_mm', 100.0, 'width_mm', 70.0, 'thickness_mm', 2.3);
end
if nargin < 2
    defects_cfg = [];
end

geom = struct();
geom.plate_length_mm = double(plate_cfg.length_mm);
geom.plate_width_mm = double(plate_cfg.width_mm);
geom.plate_thickness_mm = double(plate_cfg.thickness_mm);

geom.plate_length_m = geom.plate_length_mm * 1e-3;
geom.plate_width_m = geom.plate_width_mm * 1e-3;
geom.plate_thickness_m = geom.plate_thickness_mm * 1e-3;

has_defects = ~isempty(defects_cfg) && length(defects_cfg) > 0 && (defects_cfg(1).diameter_mm > 0);
geom.has_defect = has_defects;

if has_defects
    d = defects_cfg(1);
    geom.defect = struct(...
        'id', 1, ...
        'shape', 'cylinder', ...
        'center_x_mm', double(d.center_x_mm), ...
        'center_y_mm', double(d.center_y_mm), ...
        'depth_mm', double(d.depth_mm), ...
        'diameter_mm', double(d.diameter_mm), ...
        'thickness_mm', double(d.thickness_mm), ...
        'center_x_m', double(d.center_x_mm) * 1e-3, ...
        'center_y_m', double(d.center_y_mm) * 1e-3, ...
        'depth_m', double(d.depth_mm) * 1e-3, ...
        'diameter_m', double(d.diameter_mm) * 1e-3, ...
        'thickness_m', double(d.thickness_mm) * 1e-3, ...
        'radius_m', double(d.diameter_mm) * 1e-3 / 2.0, ...
        'area_mm2', pi * (double(d.diameter_mm) / 2.0)^2, ...
        'volume_mm3', pi * (double(d.diameter_mm) / 2.0)^2 * double(d.thickness_mm) ...
    );
else
    % Healthy control plate
    geom.defect = struct(...
        'id', 0, ...
        'shape', 'none', ...
        'center_x_mm', NaN, ...
        'center_y_mm', NaN, ...
        'depth_mm', NaN, ...
        'diameter_mm', 0.0, ...
        'thickness_mm', 0.0, ...
        'center_x_m', NaN, ...
        'center_y_m', NaN, ...
        'depth_m', NaN, ...
        'diameter_m', 0.0, ...
        'thickness_m', 0.0, ...
        'radius_m', 0.0, ...
        'area_mm2', 0.0, ...
        'volume_mm3', 0.0 ...
    );
end
end
