function result = solveForPython(config)
% SOLVEFORPYTHON Return only Python-consumed fields across the Engine boundary.
% The full solver result contains nested struct arrays for multiple defects,
% which MATLAB Engine cannot convert to Python. Keep those in the native result.
full_result = lfmt.solveTransientThermal(config);
result = struct(...
    'surface_temperature', full_result.surface_temperature, ...
    'time_vector', full_result.time_vector, ...
    'camera_x_mm', full_result.camera_x_mm, ...
    'camera_y_mm', full_result.camera_y_mm, ...
    'runtime_s', full_result.runtime_s ...
);
end
